# Build
custom_build(
    # Name of the container image
    ref = 'order-service',
    # Command to build the container image
    # On Windows, replace $EXPECTED_REF with %EXPECTED_REF%
    command = '../../gradlew bootBuildImage --imageName $EXPECTED_REF',
    # Files to watch that trigger a new build
    deps = ['build.gradle', 'src']
)

# Deploy
k8s_yaml(['../../k8s/order-service-deployment.yml', '../../k8s/order-service-service.yml'])

# Manage
k8s_resource('order-service')